### ISSUE TITLE
Some questions about the experiment performance

### ISSUE THREAD

**Issue by weitianxin** [fulifeng/Temporal_Relational_Stock_Ranking#6]
Thanks a lot for your great work. 

I run the code for several times with the command in readme. But I got the results as follows
NYSE: {mse: 2.278e-4, mrrt: 3.957e-3, btl: 1.498} NASDAQ: {'mse': 3.794e-4, mrrt: 4.840e-3, btl: 2.31}. The 'mrrt' and 'btl' seems very different from the results in your paper (RSR_I with wiki relations for NASDAQ, RSR_I with industry relations for NYSE). Are these metrics equivalent to those in your paper, or are there any other problems? 

I really hope to get the answer. Thanks very much.

**Comment by fulifeng** [comment]
The results we report in paper is an average of 5 different runs. Another point is that, as we mentioned in the paper, the variance of performance across differnt runs is high.
